apiVersion: v1
kind: Namespace
metadata:
  name: aks-dns-ag

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-dns-ag-webapp
  namespace: aks-dns-ag
  labels:
    app: aks-dns-ag-webapp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: aks-dns-ag-webapp
  template:
    metadata:
      labels:
        app: aks-dns-ag-webapp
    spec:
      containers:
      - name: aks-dns-ag-webapp
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: aks-dns-ag-webapp
  namespace: aks-dns-ag
spec:
  selector:
    app: aks-dns-ag-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aks-dns-ag-webapp
  namespace: aks-dns-ag
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aks-dns-ag-webapp
            port:
              number: 80